### Login as a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "ye@asdf.com",
    "password": "asdf"
}

### Create a new report
POST http://localhost:3000/reports/create
content-type: application/json

{
    "make": "Toyota",
    "model": "Avalon",
    "year": 2013,
    "mileage": 10000,
    "latitude": 40.7128,
    "longitude": -74.0059,
    "price": 13000
}

### Approve a report
PATCH http://localhost:3000/reports/approve/7
content-type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports/estimate?make=Toyota&model=Avalon&year=2014&latitude=40.7128&longitude=-74.0059&mileage=10000
